### ISSUE TITLE
RTL / Arabic being flipped

### ISSUE THREAD

**Issue by PascalPixel** [ForkIssues/Tracker#976]
Given:
```yml
ar:
  date:
    abbr_day_names:
    - الأحد
    - الإثنين
    - الثّلاثاء
    - الأربعاء
    - الخميس
    - الجمعة
    - السّبت
    abbr_month_names:
    -
    - يناير
    - فبراير
    - مارس
    - أبريل
    - مايو
    - يونيو
    - يوليو
    - أغسطس
    - سبتمبر
    - أكتوبر
    - نوفمبر
    - ديسمبر
    day_names:
    - الأحد
    - الإثنين
    - الثّلاثاء
    - الأربعاء
    - الخميس
    - الجمعة
    - السّبت
```

Fork displays:

<img width="385" alt="Screen Shot 2020-04-15 at 17 06 48" src="https://user-images.githubusercontent.com/3094044/79313724-beda5880-7f3b-11ea-94b2-8deeccf71527.png">
